jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        directories:
            app-entity:
                namespace_prefix: 'App\Entity'
                path: '%kernel.project_dir%/config/serializer'
