sylius_rbac:
    driver: doctrine/orm

    roles:
        ROLE_SUPERADMIN:
            name: Super administrator
            description: Super administrator user
            security_roles: [ROLE_SUPERADMIN, ROLE_ADMIN]
        ROLE_ADMIN:
            name: Administrator
            description: Administrator user
            permissions:
                - sylius.admin_user.index
                - sylius.admin_user.create
                - sylius.admin_user.update
                - sylius.locale.index
                - sylius.locale.update
                - sylius.locale.create
                - app.quiz.index
                - app.quiz.show
                - app.quiz.create
                - app.quiz.update
                - app.subject.index
                - app.subject.show
                - app.subject.create
                - app.subject.update
                - app.student_group.index
                - app.student_group.show
                - app.student_group.create
                - app.student_group.update
                - app.response.index
                - app.response.show
                - app.response.create
                - app.response.update
            security_roles: [ROLE_ADMIN]
        ROLE_TEACHER:
            name: Teacher
            description: Teacher role
            security_roles: [ROLE_TEACHER]
            permissions:
                - sylius.admin_user.update
                - app.quiz.index
                - app.quiz.show
                - app.quiz.create
                - app.quiz.update
                - app.subject.index
                - app.subject.show
                - app.subject.create
                - app.subject.update
                - app.student_group.index
                - app.student_group.show
                - app.student_group.create
                - app.student_group.update
                - app.response.index
                - app.response.show
                - app.response.create
                - app.response.update
        ROLE_STUDENT:
            name: Student
            description: Student role
            security_roles: [ROLE_STUDENT]
            permissions:
    roles_hierarchy:
        ROLE_SUPERADMIN: [ROLE_ADMIN]
