twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@PlatformAdmin/Form/Widget/subject_autocomplete_widget.html.twig'
        - '@PlatformAdmin/Form/Widget/user_autocomplete_widget.html.twig'
        - '@PlatformAdmin/Form/Widget/student_autocomplete_widget.html.twig'
        - '@PlatformAdmin/Form/Widget/student_group_autocomplete_widget.html.twig'
        - '@PlatformAdmin/Form/Widget/answer_widget.html.twig'
    paths:
        '%kernel.project_dir%/templates/bundles/PlatformFrontBundle': PlatformFront
