magephp:
    log_dir: var/log
    environments:
        production:
            user: deploy
            from: ./
            host_path: /var/www
            releases: 2
            exclude:
                - ./var/cache/*
                - ./var/log
                - ./var/sessions
                - ./var/jwt
                - ./var/uploads
                - ./tools/docker
                - ./tests
                - ./phpunit.xml.dist
                - ./.mage.yml
                - ./package.json
                - ./package-lock.json
                - ./README.md
                - ./composer.lock
                - ./gulpfile.babel.js
                - ./.gitignore
                - ./public/.htaccess
                - ./node_modules
            hosts:
                - ec2-35-158-197-11.eu-central-1.compute.amazonaws.com
            pre-deploy:
            on-deploy:
                - exec: { cmd: 'setfacl -R -m:rwx -m u:www-data:rwX -m u:deploy:rwX var', desc: "Cache permissions (Current objects)" }
                - exec: { cmd: 'setfacl -dR -m:rwx -m u:www-data:rwX -m u:deploy:rwX var', desc: "Cache permissions (New objects)" }
                - fs/link: { from: '../../../shared/.htaccess', to: 'public/.htaccess' }
                - fs/link: { from: '../../shared/.env.local', to: '.env.local' }
                - symfony/cache-warmup: { env: 'prod' }
                - exec: { cmd: 'bin/console doctrine:cache:clear-result --env=prod', desc: "doctrine:cache:clear-result"}
                - exec: { cmd: 'bin/console doctrine:cache:clear-query --env=prod', desc: "doctrine:cache:clear-query"}
                - exec: { cmd: 'bin/console doctrine:cache:clear-metadata --env=prod', desc: "doctrine:cache:clear-metadata"}
                - exec: { cmd: 'bin/console doctrine:migrations:migrate --no-interaction --env=prod', desc: "doctrine:migrations:migrate" }
                - exec: { cmd: 'bin/console sylius:rbac:initialize --env=prod', desc: "sylius:rbac:initialize"}
            on-release:
            post-release:
            post-deploy:
