app_quiz:
    resource: |
        alias: app.quiz
        templates: PlatformAdminBundle:Crud
        except: ['show', 'bulkDelete', 'delete']
        redirect: index
        grid: app_quiz
        vars:
            all:
                subheader: app.ui.manage_quizzes
            index:
                icon: globe
    type: sylius.resource

app_quiz_show:
    path: /quizzes/{id}
    methods: [GET]
    defaults:
        _controller: app.controller.quiz:showAction
        _sylius:
            section: admin
            permission: true
            template: "@PlatformAdmin/Quiz/show.html.twig"
