sylius_grid:
    grids:
        admin_platform_admin_user:
            driver:
                name: '%admin_platform.driver%'
                options:
                    class: "%sylius.model.admin_user.class%"
                    repository:
                        method: createQueryBuilderByRoles
                        arguments:
                            - !php/const App\Constants\AuthorizationRoles::ADMIN_ROLES
