app_response_answer_update:
    path: /responses/{uuid}/answer/{id}
    methods: [GET, POST]
    defaults:
        _controller: app.controller.response_answer:updateAnswerAction
        _sylius:
            template: "@PlatformFront/ResponseAnswer/show.html.twig"
            form: App\Form\Type\Response\ResponseAnswerType
            flash: false
            repository:
                method: findOneByUuidAndId
                arguments:
                    uuid: $uuid
                    id: $id
