app_admin_ajax_user_by_name:
    path: /users/search
    methods: [GET]
    defaults:
        _controller: sylius.controller.admin_user:indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findByNamePart
                arguments:
                    phrase: $phrase
                    role: !php/const App\Constants\AuthorizationRoles::ROLE_TEACHER
                    limit: 25

app_admin_ajax_user_by_id:
    path: /users/id
    methods: [GET]
    defaults:
        _controller: sylius.controller.admin_user:indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findBy
                arguments: [id: $id]
